# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_name', models.CharField(max_length=255)),
                ('data_source', models.CharField(choices=[('ENCODE', 'ENCODE'), ('GEO', 'GEO'), ('Array Express', 'AE')], max_length=16)),
                ('cell_line', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=16)),
                ('jaspar_id', models.CharField(blank=True, max_length=16)),
                ('jaspar_version', models.CharField(blank=True, max_length=1)),
                ('folder', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_caller', models.CharField(choices=[('MACS', 'MACS'), ('BCP', 'BCP'), ('HOMER', 'HOMER')], max_length=16)),
                ('prediction_model', models.CharField(choices=[('PWM', 'PWM'), ('DiMO', 'DiMO'), ('TFFM', 'TFFM'), ('DNAShaped', 'DNAShaped'), ('NRG', 'NRG')], max_length=16)),
                ('model_detail', models.CharField(max_length=150)),
                ('folder', models.CharField(max_length=255)),
                ('jaspar_id', models.CharField(blank=True, max_length=16)),
                ('jaspar_version', models.CharField(blank=True, max_length=1)),
                ('distance_threshold', models.CharField(max_length=16)),
                ('score_threshold', models.CharField(max_length=16)),
                ('adj_centrimo_pvalue', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('Update', 'Update'), ('Bug fix', 'Bug fix'), ('Announcement', 'Announcement'), ('Other', 'Other')], max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
