# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='biological_condition',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
