# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_factor_biological_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factordata',
            name='folder',
            field=models.ForeignKey(db_column='folder', on_delete=django.db.models.deletion.CASCADE, to='portal.Factor', to_field='folder'),
        ),
    ]
