# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180304_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factordata',
            name='model_detail',
        ),
    ]
