# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_factor_biological_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='factordata',
            name='model_detail',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='factordata',
            name='prediction_model',
            field=models.CharField(choices=[('PWM', 'PWM'), ('DiMO', 'DiMO'), ('TFFM', 'TFFM'), ('DNAShaped_4bits', 'DNAShaped_4bits'), ('DNAShaped_pssm', 'DNAShaped_pssm'), ('DNAShaped_tffm', 'DNAShaped_tffm'), ('NRG', 'NRG')], max_length=16),
        ),
    ]
