# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20180618_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='total_peaks',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='factordata',
            name='total_tfbs',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
